USE TTTH;
GO

-- Proc themhocvien
IF OBJECT_ID('THEMHOCVIEN', 'P') IS NOT NULL
DROP PROC THEMHOCVIEN
GO
CREATE PROCEDURE THEMHOCVIEN
	@cmnd char(12),
	@tenhv nvarchar(30),
	@diachi nvarchar(100),
	@sdt varchar(12),
	@email VARCHAR(100)
AS
	declare @temp int;
	set @temp = (select COUNT(*) from HOCVIEN) + 1;
	declare @mahocvien char(4);
	set @mahocvien = 'HV' + cast(@temp as nvarchar);
	insert into NGUOITHAMGIA values(@cmnd);
	insert into HOCVIEN values(@mahocvien,@cmnd,@tenhv,@diachi,@sdt,@email);
GO

-- Proc hienthi
IF OBJECT_ID('HIENTHI', 'P') IS NOT NULL
DROP PROC HIENTHI
GO

CREATE PROCEDURE HIENTHI
AS
	select tenhp, tengv, tongsl, giahocphan, namhoc, hocky,
	tiet, ngay, loaihp, hocphan.MAHP as mahp, 
	MAHP_COBAN, TENHP_COBAN
	from hocphan
	join HOCPHANMO on hocphan.MAHP = HOCPHANMO.MAHP and HOCKY != 0
	join GIAOVIEN on GIAOVIEN.MAGV = HOCPHANMO.MAGV;
	
GO

-- Proc tracuuketqua
IF OBJECT_ID('TRACUUKETQUA', 'P') IS NOT NULL
DROP PROC TRACUUKETQUA
GO	
CREATE PROCEDURE TRACUUKETQUA
	@MAHV CHAR(4),
	@MAHP CHAR(4)
AS
	DECLARE @RES INT
	IF EXISTS(SELECT * FROM KETQUAHOCPHAN WHERE MAHV=@MAHV AND MAHP=@MAHP)
	BEGIN
		SELECT HOCVIEN.MAHV,TENHV,HOCPHAN.MAHP,TENHP,NAMHOC,HOCKY,DIEMHOCPHAN,NGAYCAPCHUNGCHI AS NGAY
			FROM KETQUAHOCPHAN,HOCPHAN,HOCVIEN WHERE KETQUAHOCPHAN.MAHV=@MAHV AND KETQUAHOCPHAN.MAHP=@MAHP 
			AND KETQUAHOCPHAN.MAHV=HOCVIEN.MAHV AND KETQUAHOCPHAN.MAHP=HOCPHAN.MAHP;
	END
	ELSE 
	BEGIN
		SELECT * FROM KETQUAHOCPHAN WHERE 1!=1;
	END
GO

-- Proc laymahocvien
IF OBJECT_ID('LAYMAHOCVIEN', 'P') IS NOT NULL
DROP PROC LAYMAHOCVIEN
GO
CREATE PROCEDURE LAYMAHOCVIEN
@CMND CHAR(12)
AS
	select MAHV
	from HOCVIEN WHERE CMND = @CMND;
GO

-- Proc themhocphan
IF OBJECT_ID('THEMHOCPHAN', 'P') IS NOT NULL
DROP PROC THEMHOCPHAN
GO
CREATE PROCEDURE THEMHOCPHAN
	@MAHP CHAR(4),
	@NAMHOC CHAR(4),
	@HOCKY INT,
	@MAHV CHAR(4),
	@MANV CHAR(4),
	@NGAY NVARCHAR(30)
AS
	INSERT INTO DANGKY VALUES (@MAHP,@NAMHOC,@HOCKY,@MAHV,@MANV,@NGAY);
	UPDATE HOCPHANMO
	SET TONGSL = TONGSL + 1
	WHERE MAHP = @MAHP and NAMHOC = @NAMHOC AND HOCKY = @HOCKY;
GO

-- Proc themhocphanhvm
IF OBJECT_ID('THEMHOCPHANHVM', 'P') IS NOT NULL
DROP PROC THEMHOCPHANHVM
GO
CREATE PROCEDURE THEMHOCPHANHVM
	@MAHP CHAR(4),
	@NAMHOC CHAR(4),
	@HOCKY INT,
	@MAHV CHAR(4),
	@MANV CHAR(4),
	@NGAY NVARCHAR(30)
AS
	INSERT INTO DANGKY VALUES (@MAHP,@NAMHOC,@HOCKY,@MAHV,@MANV,@NGAY);
	INSERT INTO KETQUAHOCPHAN VALUES (@MAHP,@NAMHOC,@HOCKY,@MAHV,0,NULL,NULL,0);
	UPDATE HOCPHANMO
	SET TONGSL = TONGSL + 1
	WHERE MAHP = @MAHP and NAMHOC = @NAMHOC AND HOCKY = @HOCKY;
GO

-- Proc xoahocphan
IF OBJECT_ID('XOAHOCPHAN', 'P') IS NOT NULL
DROP PROC XOAHOCPHAN
GO
CREATE PROCEDURE XOAHOCPHAN
	@MAHP CHAR(4),
	@NAMHOC CHAR(4),
	@HOCKY INT,
	@MAHV CHAR(4)
AS
	IF EXISTS(SELECT MAHP FROM KETQUAHOCPHAN WHERE MAHP = @MAHP AND NAMHOC = @NAMHOC AND DIEMHOCPHAN = 0 AND MAHV = @MAHV AND HOCKY = @HOCKY
	 AND NGAYCAPCHUNGCHI IS NULL AND NGAYTHILAI IS NULL)
	BEGIN 
		DELETE FROM KETQUAHOCPHAN WHERE MAHP = @MAHP and NAMHOC = @NAMHOC AND DIEMHOCPHAN = 0 AND MAHV = @MAHV AND NGAYCAPCHUNGCHI IS NULL AND
		NGAYTHILAI IS NULL AND HOCKY = @HOCKY;
	END
	DELETE FROM DANGKY WHERE MAHP = @MAHP and NAMHOC = @NAMHOC AND HOCKY = @HOCKY AND MAHV = @MAHV;
	UPDATE HOCPHANMO
	SET TONGSL = TONGSL - 1
	WHERE MAHP = @MAHP and NAMHOC = @NAMHOC AND HOCKY = @HOCKY;
GO

-- Proc kiemtrahvtontai
IF OBJECT_ID('KIEMTRAHVTONTAI', 'P') IS NOT NULL
DROP PROC KIEMTRAHVTONTAI
GO
CREATE PROCEDURE KIEMTRAHVTONTAI 
	@MAHV CHAR(4)
AS 
BEGIN
	DECLARE @RES INT
	IF EXISTS(SELECT * FROM HOCVIEN WHERE MAHV=@MAHV)
	BEGIN 
		SET @RES = 1
		RETURN @RES
	END
	ELSE	
	BEGIN
		SET @RES = 0
		RETURN @RES
	END
END
GO

-- Proc kiemtrahptontai
IF OBJECT_ID('KIEMTRAHPTONTAI', 'P') IS NOT NULL
DROP PROC KIEMTRAHPTONTAI
GO
CREATE PROCEDURE KIEMTRAHPTONTAI 
	@MAHP CHAR(4)
AS 
BEGIN
	DECLARE @RES INT
	IF EXISTS(SELECT * FROM HOCPHAN WHERE MAHP=@MAHP)
	BEGIN 
		SET @RES = 1
		RETURN @RES
	END
	ELSE	
	BEGIN
		SET @RES = 0
		RETURN @RES
	END
END
GO

-- Proc kiemtrahocphancoban
IF OBJECT_ID('KIEMTRAHOCPHANCOBAN', 'P') IS NOT NULL
DROP PROC KIEMTRAHOCPHANCOBAN
GO
CREATE PROCEDURE KIEMTRAHOCPHANCOBAN 
	@MAHP CHAR(4), 
	@MAHV CHAR(4)
AS 
BEGIN
	DECLARE @RES INT
	IF EXISTS(SELECT * FROM KETQUAHOCPHAN WHERE MAHP=@MAHP AND MAHV = @MAHV AND NGAYCAPCHUNGCHI IS NOT NULL)
	BEGIN 
		SET @RES = 1
		RETURN @RES
	END
	ELSE	
	BEGIN
		SET @RES = 0
		RETURN @RES
	END
END
GO

-- Proc kiemtracmnd
IF OBJECT_ID('KIEMTRACMND', 'P') IS NOT NULL
DROP PROC KIEMTRACMND
GO
CREATE PROCEDURE KIEMTRACMND 
	@cmnd char(12)
AS 
BEGIN
	DECLARE @RES INT
	IF EXISTS(SELECT * FROM HOCVIEN WHERE CMND = @cmnd)
	BEGIN 
		SET @RES = 1
		RETURN @RES
	END
	ELSE	
	BEGIN
		SET @RES = 0
		RETURN @RES
	END
END
GO



------Tấn làm xem ds giáo viên + Xếp phòng---------------------------------------------------------------------

--Xem danh sách giáo viên
if object_id('Proc_XemDSGV', 'P') is not null
drop proc Proc_XemDSGV
go
create proc Proc_XemDSGV
as
	select * from giaovien;
go
exec Proc_XemDSGV


--Xếp phòng
if object_id('Proc_XepPhong', 'P') is not null
drop proc Proc_XepPhong
go
create proc Proc_XepPhong
	@mahp char(4),
	@namhoc char(4),
	@hocky int,
	@tenphonghoc nvarchar(100)
as
	if exists(select * from chitietphonghoc 
			  where @mahp = mahp and @namhoc = namhoc and @hocky = hocky and @tenphonghoc = tenphonghoc)
	begin
		print('Trung');
	end

	insert into chitietphonghoc(mahp, namhoc, hocky, tenphonghoc) values (@mahp, @namhoc, @hocky, @tenphonghoc);
go

--exec Proc_XepPhong 'HP01','2021',2,'I21'



---Ân : đăng ký thi chứng chỉ quốc tế---------------------------------------------------------------------
if object_id('DANGKYTHICCQT_KHAC ', 'P') is not null
drop proc DANGKYTHICCQT_KHAC 
go
create proc DANGKYTHICCQT_KHAC 
	@CMND VARCHAR(12),
	@HOTEN NVARCHAR(30),
	@DIACHI NVARCHAR(100),
	@SDT VARCHAR(12),
	@EMAIL VARCHAR(100),
	@MACCQT VARCHAR(4),
	@DOTTHI VARCHAR(30)
AS
	INSERT INTO NGUOITHAMGIA VALUES (@CMND);
	INSERT INTO DOITUONGKHAC VALUES(@CMND,@HOTEN,@DIACHI,@SDT,@EMAIL);

	DECLARE @NGAYLAP VARCHAR(20)=GETDATE()
	DECLARE @N CHAR(2) = (SELECT COUNT(*)+1 FROM HD_CHUNGCHI);
	DECLARE @MAHD CHAR(4) = CONCAT('HC',@N);
	DECLARE @GIACHUNGCHI FLOAT = (SELECT PHICAPCHUNGCHI + LEPHITHI FROM CHUNGCHIQUOCTE WHERE MACCQT=@MACCQT)
	INSERT INTO HD_CHUNGCHI VALUES(@MAHD,@CMND,NULL,@GIACHUNGCHI,@NGAYLAP,NULL);
	INSERT INTO CTHD_CHUNGCHI VALUES (@MACCQT, @MAHD, @GIACHUNGCHI);
	INSERT INTO PHIEUDUTHI VALUES (@CMND, @MACCQT, @MAHD, @DOTTHI,N'CƠ SỞ NGUYỄN VĂN CỪ');

GO
if object_id('DANGKYTHICCQT_HV ', 'P') is not null
drop proc DANGKYTHICCQT_HV 
go
CREATE PROC DANGKYTHICCQT_HV
	@MAHV CHAR(4),
	@HOTEN NVARCHAR(50),
	@CMND VARCHAR(12),
	@MACCQT VARCHAR(4),
	@DOTTHI VARCHAR(30)
AS

	DECLARE @NGAYLAP VARCHAR(20)=GETDATE()
	DECLARE @N CHAR(2) = (SELECT COUNT(*)+1 FROM HD_CHUNGCHI);
	DECLARE @MAHD CHAR(4) = CONCAT('HC',@N);
	DECLARE @GIACHUNGCHI FLOAT = (SELECT PHICAPCHUNGCHI + LEPHITHI FROM CHUNGCHIQUOCTE WHERE MACCQT=@MACCQT)
	INSERT INTO HD_CHUNGCHI VALUES(@MAHD,@CMND,NULL,0.9*@GIACHUNGCHI,@NGAYLAP,NULL);
	INSERT INTO CTHD_CHUNGCHI VALUES (@MACCQT, @MAHD, 0.9*@GIACHUNGCHI);
	INSERT INTO PHIEUDUTHI VALUES (@CMND, @MACCQT, @MAHD, @DOTTHI,N'CƠ SỞ NGUYỄN VĂN CỪ');
go