--TẠO CSDL
USE master
GO
IF DB_ID('TTTH') IS NOT NULL 
	DROP DATABASE TTTH 
GO
CREATE DATABASE TTTH
GO 
USE TTTH
GO

--KIỂM TRA XEM CAC BẢNG ĐÃ TỒN TẠI HAY CHƯA. NẾU ĐÃ TỒN TẠI THÌ DROP
IF OBJECT_ID (N'CHITIETPHONGHOC', N'U') IS NOT NULL
	DROP TABLE CHITIETPHONGHOC
IF OBJECT_ID (N'KETQUAHOCPHAN', N'U') IS NOT NULL
	DROP TABLE KETQUAHOCPHAN
IF OBJECT_ID (N'DS_CHUNGCHI', N'U') IS NOT NULL
	DROP TABLE DS_CHUNGCHI
IF OBJECT_ID (N'CTHD_CHUNGCHI', N'U') IS NOT NULL
	DROP TABLE CTHD_CHUNGCHI
IF OBJECT_ID (N'PHIEUDUTHI', N'U') IS NOT NULL
	DROP TABLE PHIEUDUTHI
IF OBJECT_ID (N'CTHD_HOCPHAN', N'U') IS NOT NULL
	DROP TABLE CTHD_HOCPHAN
IF OBJECT_ID (N'HOCPHANMO', N'U') IS NOT NULL
	DROP TABLE HOCPHANMO
IF OBJECT_ID (N'HD_CHUNGCHI', N'U') IS NOT NULL
	DROP TABLE HD_CHUNGCHI
IF OBJECT_ID (N'CHUNGCHIQUOCTE', N'U') IS NOT NULL
	DROP TABLE CHUNGCHIQUOCTE
IF OBJECT_ID (N'DOITUONGKHAC', N'U') IS NOT NULL
	DROP TABLE DOITUONGKHAC
IF OBJECT_ID (N'HOADONHOCPHAN', N'U') IS NOT NULL
	DROP TABLE HOADONHOCPHAN
IF OBJECT_ID (N'CHUNGCHI', N'U') IS NOT NULL
	DROP TABLE CHUNGCHI
IF OBJECT_ID (N'CONGTY', N'U') IS NOT NULL
	DROP TABLE CONGTY
IF OBJECT_ID (N'DANGKY', N'U') IS NOT NULL
	DROP TABLE DANGKY
IF OBJECT_ID (N'HOCVIEN', N'U') IS NOT NULL
	DROP TABLE HOCVIEN
IF OBJECT_ID (N'NGUOITHAMGIA', N'U') IS NOT NULL
	DROP TABLE NGUOITHAMGIA
IF OBJECT_ID (N'KHOAHOC', N'U') IS NOT NULL
	DROP TABLE KHOAHOC
IF OBJECT_ID (N'HOCPHAN', N'U') IS NOT NULL
	DROP TABLE HOCPHAN
IF OBJECT_ID (N'GIAOVIEN', N'U') IS NOT NULL
	DROP TABLE GIAOVIEN
IF OBJECT_ID (N'PHONGHOC', N'U') IS NOT NULL
	DROP TABLE PHONGHOC
IF OBJECT_ID (N'NHANVIEN', N'U') IS NOT NULL
	DROP TABLE NHANVIEN


--TẠO BẢNG
CREATE TABLE CHUNGCHIQUOCTE
(
	MACCQT VARCHAR(4),
	TENCCQT NVARCHAR(40),
	PHICAPCHUNGCHI FLOAT,
	LEPHITHI FLOAT
	CONSTRAINT PK_CCQT PRIMARY KEY (MACCQT)
)

CREATE TABLE CTHD_CHUNGCHI
(
	MACCQT VARCHAR(4),
	MAHD CHAR(4),
	GIACHUNGCHI FLOAT,
	CONSTRAINT PK_CTHD_CC PRIMARY KEY (MACCQT, MAHD)
)

CREATE TABLE HD_CHUNGCHI
(
	MAHD CHAR(4),
	CMND CHAR(12),
	MANV CHAR(4),
	TONGTIEN FLOAT,
	NGAYLAP NVARCHAR(30),
	THANHTOAN NVARCHAR(100)
	CONSTRAINT PK_HD_CHUNGCHI PRIMARY KEY (MAHD)
)

CREATE TABLE PHIEUDUTHI
(
	CMND CHAR(12),
	MACCQT VARCHAR(4),
	MAHD CHAR(4),
	THOIGIANDUTHI NVARCHAR(30),
	DIADIEMTHI NVARCHAR(100)
	CONSTRAINT PK_PHIEUDUTHI PRIMARY KEY (CMND, MACCQT)
)

CREATE TABLE NGUOITHAMGIA
(
	CMND CHAR(12)
	CONSTRAINT PK_NGUOITHAMGIA PRIMARY KEY (CMND)
)

CREATE TABLE DOITUONGKHAC
(
	CMND CHAR(12),
	HOTEN NVARCHAR(30),
	DIACHI NVARCHAR(100),
	SDT VARCHAR(12),
	EMAIL VARCHAR(100)
	CONSTRAINT PK_DOITUONGKHAC PRIMARY KEY (CMND)
)

CREATE TABLE HOCVIEN
(
	MAHV CHAR(4),
	CMND CHAR(12) UNIQUE,
	TENHV NVARCHAR(30),
	DIACHI NVARCHAR(100),
	SDT VARCHAR(12),
	EMAIL VARCHAR(100)
	CONSTRAINT PK_HOCVIEN PRIMARY KEY (MAHV)
)

CREATE TABLE CHUNGCHI
(
	MACHUNGCHI CHAR(4),
	TENCHUNGCHI NVARCHAR(50)
	CONSTRAINT PK_CHUNGCHI PRIMARY KEY (MACHUNGCHI)
)

CREATE TABLE DS_CHUNGCHI
(
	MACHUNGCHI CHAR(4),
	MAHV CHAR(4)
	CONSTRAINT PK_DSCHUNGCHI PRIMARY KEY (MACHUNGCHI, MAHV)
)

CREATE TABLE KETQUAHOCPHAN
(
	MAHP CHAR(4),
	NAMHOC CHAR(4),
	HOCKY INT,
	MAHV CHAR(4),
	DIEMHOCPHAN FLOAT,
	NGAYCAPCHUNGCHI NVARCHAR(30),
	NGAYTHILAI NVARCHAR(30),
	SOLANTHILAI INT
	CONSTRAINT PK_KETQUAHOCPHAN PRIMARY KEY (MAHP, NAMHOC, HOCKY, MAHV)
)

CREATE TABLE DANGKY
(
	MAHP CHAR(4),
	NAMHOC CHAR(4),
	HOCKY INT,
	MAHV CHAR(4),
	MANV CHAR(4),
	NGAY NVARCHAR(30)
	CONSTRAINT PK_DANGKY PRIMARY KEY (MAHP, NAMHOC, HOCKY, MAHV)
)

CREATE TABLE HOCPHANMO
(
	MAHP CHAR(4),
	NAMHOC CHAR(4),
	HOCKY INT,
	MAGV CHAR(4),
	TONGSL INT,
	GIAHOCPHAN FLOAT,
	TIET INT,
	NGAY NVARCHAR(30)
	CONSTRAINT PK_HOCPHANMO PRIMARY KEY (MAHP, NAMHOC, HOCKY)
)

CREATE TABLE CONGTY
(
	MASOTHUE CHAR(4),
	MAHV CHAR(4),
	TENCONGTY NVARCHAR(100)
	CONSTRAINT PK_CONGTY PRIMARY KEY (MASOTHUE,MAHV)
)

CREATE TABLE HOADONHOCPHAN
(
	MAHD CHAR(4),
	MANV CHAR(4),
	MAHV CHAR(4),
	TONGTIEN FLOAT,
	NGAYLAP NVARCHAR(30),
	THANHTOAN NVARCHAR(100)
	CONSTRAINT PK_HDHP PRIMARY KEY (MAHD)
)

CREATE TABLE CTHD_HOCPHAN
(
	MAHP CHAR(4),
	NAMHOC CHAR(4),
	HOCKY INT,
	MAHD CHAR(4)
	CONSTRAINT PK_CTHD_HOCPHAN PRIMARY KEY (MAHP, NAMHOC, HOCKY, MAHD)
)

CREATE TABLE CHITIETPHONGHOC
(
	MAHP CHAR(4),
	NAMHOC CHAR(4),
	HOCKY INT,
	TENPHONGHOC NVARCHAR(100)
	CONSTRAINT PK_CTPHONGHOC PRIMARY KEY (MAHP, NAMHOC, HOCKY, TENPHONGHOC)
)

CREATE TABLE PHONGHOC
(
	TENPHONGHOC NVARCHAR(100)
	CONSTRAINT PK_PHONGHOC PRIMARY KEY (TENPHONGHOC)
)

CREATE TABLE KHOAHOC
(
	NAMHOC CHAR(4),
	HOCKY INT
	CONSTRAINT PK_KHOAHOC PRIMARY KEY (NAMHOC,HOCKY)
)

CREATE TABLE HOCPHAN
(
	MAHP CHAR(4),
	TENHP NVARCHAR(30),
	LOAIHP CHAR(1),
	MAHP_COBAN CHAR(4),
	TENHP_COBAN NVARCHAR(30)
	CONSTRAINT PK_HOCPHAN PRIMARY KEY (MAHP)
)

CREATE TABLE GIAOVIEN
(
	MAGV CHAR(4),
	TENGV NVARCHAR(30),
	SDT VARCHAR(12),
	EMAIL VARCHAR(100),
	DIACHI NVARCHAR(100),
	TINHTRANG NVARCHAR(20)
	CONSTRAINT PK_GIAOVIEN PRIMARY KEY (MAGV)
)

CREATE TABLE NHANVIEN
(
	MANV CHAR(4),
	TENNV NVARCHAR(30),
	SDT VARCHAR(12),
	EMAIL VARCHAR(100),
	DIACHI NVARCHAR(100),
	LOAINHANVIEN NVARCHAR(10)
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
)

----------------TẠO KHÓA NGOẠI-------------------
--HOCPHAN --> HOCPHAN
ALTER TABLE HOCPHAN
ADD
	CONSTRAINT FK_HPNC_HPCB
	FOREIGN KEY (MAHP_COBAN)
	REFERENCES HOCPHAN(MAHP)


--CTHD_CHUNGCHI -->	CHUNGCHIQUOCTE
ALTER TABLE CTHD_CHUNGCHI
ADD
	CONSTRAINT FK_CTHD_CCQT
	FOREIGN KEY (MACCQT) 
	REFERENCES CHUNGCHIQUOCTE(MACCQT)

--CTHD_CHUNGCHI --> HD_CHUNGCHI	
ALTER TABLE CTHD_CHUNGCHI
ADD
	CONSTRAINT FK_CTHD_HDCC
	FOREIGN KEY (MAHD) 
	REFERENCES HD_CHUNGCHI(MAHD)

--HD_CHUNGCHI --> NGUOITHAMGIA
ALTER TABLE HD_CHUNGCHI
ADD
	CONSTRAINT FK_HDCC_NGUOITHAMGIA
	FOREIGN KEY (CMND) 
	REFERENCES NGUOITHAMGIA(CMND)

--HD_CHUNGCHI --> NHANVIEN
ALTER TABLE HD_CHUNGCHI
ADD
	CONSTRAINT FK_HDCC_NHANVIEN
	FOREIGN KEY (MANV)
	REFERENCES NHANVIEN(MANV)

--PHIEUDUTHI --> HD_CHUNGCHI
ALTER TABLE PHIEUDUTHI
ADD
	CONSTRAINT FK_PDT_HDCC
	FOREIGN KEY (MAHD)
	REFERENCES HD_CHUNGCHI(MAHD)

--PHIEUDUTHI --> CHUNGCHIQUOCTE
ALTER TABLE PHIEUDUTHI
ADD
	CONSTRAINT FK_PDT_CCQT
	FOREIGN KEY (MACCQT)
	REFERENCES CHUNGCHIQUOCTE(MACCQT)

--PHIEUDUTHI --> NGUOITHAMGIA
ALTER TABLE PHIEUDUTHI
ADD
	CONSTRAINT FK_PDT_NGUOITHAMGIA
	FOREIGN KEY (CMND)
	REFERENCES NGUOITHAMGIA(CMND)

--DOITUONGKHAC --> NGUOITHAMGIA
ALTER TABLE DOITUONGKHAC
ADD
	CONSTRAINT FK_DTK_NGUOITHAMGIA
	FOREIGN KEY (CMND)
	REFERENCES NGUOITHAMGIA(CMND)

--HOCVIEN --> NGUOITHAMGIA
ALTER TABLE HOCVIEN
ADD
	CONSTRAINT FK_HV_NGUOITHAMGIA
	FOREIGN KEY (CMND)
	REFERENCES NGUOITHAMGIA(CMND)

--DS_CHUNGCHI --> CHUNGCHI
ALTER TABLE DS_CHUNGCHI
ADD
	CONSTRAINT FK_DSCC_CHUNGCHI
	FOREIGN KEY (MACHUNGCHI)
	REFERENCES CHUNGCHI(MACHUNGCHI)

--DS_CHUNGCHI --> HOCVIEN
ALTER TABLE DS_CHUNGCHI
ADD
	CONSTRAINT FK_DSCC_HOCVIEN
	FOREIGN KEY (MAHV)
	REFERENCES HOCVIEN(MAHV)

--KETQUAHOCPHAN --> DANGKY
ALTER TABLE KETQUAHOCPHAN
ADD
	CONSTRAINT FK_KQHP_DANGKY
	FOREIGN KEY (MAHP,NAMHOC,HOCKY,MAHV)
	REFERENCES DANGKY(MAHP,NAMHOC,HOCKY,MAHV)

--DANGKY --> HOCVIEN
ALTER TABLE DANGKY
ADD
	CONSTRAINT FK_DANGKY_HOCVIEN
	FOREIGN KEY (MAHV)
	REFERENCES HOCVIEN(MAHV)

--DANGKY --> HOCPHANMO
ALTER TABLE DANGKY
ADD
	CONSTRAINT FK_DANGKY_HOCPHANMO
	FOREIGN KEY (MAHP,NAMHOC,HOCKY)
	REFERENCES HOCPHANMO(MAHP,NAMHOC,HOCKY)

--DANGKY --> NHANVIEN
ALTER TABLE DANGKY
ADD
	CONSTRAINT FK_DANGKY_NHANVIEN
	FOREIGN KEY (MANV)
	REFERENCES NHANVIEN(MANV)

--HOADONHOCPHAN --> NHANVIEN
ALTER TABLE HOADONHOCPHAN
ADD
	CONSTRAINT FK_HOADONHOCPHAN_NHANVIEN
	FOREIGN KEY (MANV)
	REFERENCES NHANVIEN(MANV)

--HOADONHOCPHAN --> HOCVIEN
ALTER TABLE HOADONHOCPHAN
ADD
	CONSTRAINT FK_HOADONHOCPHAN_HOCVIEN
	FOREIGN KEY (MAHV)
	REFERENCES HOCVIEN(MAHV)

--CTHD_HOCPHAN --> HOADONHOCPHAN
ALTER TABLE CTHD_HOCPHAN
ADD
	CONSTRAINT FK_CTHDHP_HDHP
	FOREIGN KEY (MAHD)
	REFERENCES HOADONHOCPHAN(MAHD)

--CTHD_HOCPHAN --> HOCPHANMO
ALTER TABLE CTHD_HOCPHAN
ADD
	CONSTRAINT FK_CTHDHP_HPM
	FOREIGN KEY (MAHP,NAMHOC,HOCKY)
	REFERENCES HOCPHANMO(MAHP,NAMHOC,HOCKY)

--CHITIETPHONGHOC --> HOCPHANMO
ALTER TABLE CHITIETPHONGHOC
ADD
	CONSTRAINT PK_CTPH_HPM
	FOREIGN KEY (MAHP,NAMHOC,HOCKY)
	REFERENCES HOCPHANMO(MAHP,NAMHOC,HOCKY)

--CHITIETPHONGHOC --> PHONGHOC
ALTER TABLE CHITIETPHONGHOC
ADD
	CONSTRAINT PK_CTPH_PHONGHOC
	FOREIGN KEY (TENPHONGHOC)
	REFERENCES PHONGHOC(TENPHONGHOC)

--CONGTY --> HOCVIEN
ALTER TABLE CONGTY
ADD
	CONSTRAINT PK_CONGTY_HOCVIEN
	FOREIGN KEY (MAHV)
	REFERENCES HOCVIEN(MAHV)

--HOCPHANMO --> GIAOVIEN
ALTER TABLE HOCPHANMO
ADD
	CONSTRAINT PK_HOCPHANMO_GIAOVIEN
	FOREIGN KEY (MAGV)
	REFERENCES GIAOVIEN(MAGV)

--HOCPHANMO --> HOCPHAN
ALTER TABLE HOCPHANMO
ADD
	CONSTRAINT PK_HOCPHANMO_HOCPHAN
	FOREIGN KEY (MAHP)
	REFERENCES HOCPHAN(MAHP)

--HOCPHANMO --> KHOAHOC
ALTER TABLE HOCPHANMO
ADD
	CONSTRAINT PK_HOCPHANMO_KHOAHOC
	FOREIGN KEY (NAMHOC,HOCKY)
	REFERENCES KHOAHOC(NAMHOC,HOCKY)

